import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { inter } from "./font.config";

const fontInter = inter;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${fontInter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
